services:
  player:
    build: .
    container_name: player-ticia
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - ADMIN_USER=admin
      - ADMIN_PASS=SenhaFORTE101
      - TZ=America/Sao_Paulo
    volumes:
      - ./music:/usr/src/app/music
      - ./data:/usr/src/app/data
      - ./public:/usr/src/app/public
      - ./produtos-monitorados.json:/usr/src/app/produtos-monitorados.json
    restart: always

